# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:

- job: 'Build'
  timeoutInMinutes: 0

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      make docker
    displayName: 'make docker all arch'