name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install apt-cacher
      run: 
        apt-get install apt-cacher-ng
        apt-cacher-ng
    - name: build
      run: tools/autobuild/build.sh
